config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get  'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end
  root 'items#index'
 
  resources :items do
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :credits,only:[:index,:new,:show,:edit,:update]do
    collection do
      #payjpでトークン化を行う
      post 'pay', to: 'credits#pay'
      #カード削除
      post 'delete', to: 'credits#delete'
      #カード情報入力
      post 'show', to: 'credits#show'
    end
  end
    
  resources :users do
    collection do
      post 'buy',to: 'users#buy'
      get  'done_buy',to: 'users#done_buy'
    end
    member do
      get 'confirm'
    end
  end
  resources :brands
  resources :comments
  resources :destinations
  resources :categories, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable
  
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :evaluations
  has_many :seller_items, foreign_key: "seller_id", class_name: "items"
  has_many :buyer_items, foreign_key: "buyer_id", class_name: "items"
  # has_one :profile, dependent: :destroy
  has_one :destination, dependent: :destroy
  has_one :credit, dependent: :destroy  
  
  # accepts_nested_attributes_for :destination

  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: true } , format: {with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: 'には@とドメインを含めて下さい'}

  validates :password, presence: true
  
  validates :family_name,:first_name, presence: true, format: { with:/\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々]|[a-zA-Z]|[ａ-ｚＡ-Ｚ])+\z/, message: 'は全角で入力して下さい'}
  
  validates :family_name_kana,:first_name_kana, presence: true, format: { with: /\A[ぁ-んー－]+\z/, message: 'は全角ひらがなで入力して下さい'}

  validates :birth_date, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create,:new]
  # before_action :configure_account_update_params, only: [:update]
  def new
    @user = User.new
  end

  def create
    date = params[:birth_date]
    params[:user][:birth_date] = birth_date_join(date)

    #登録1ページ目から送られてきたパラメータを@userに代入
    @user = User.new(sign_up_params) 
    
    #validメソッドを使ってバリデーションチェック。これを書かないとモデルでかけたバリデーションが効かない
    unless @user.valid? 
      flash.now[:alert] = @user.errors.full_messages
      render :new and return #and returnを使って条件分岐を明示的に終了させている。
    end
    

   
    session["devise.regist_data"] = {user: @user.attributes} 
    #sessionにハッシュオブジェクトで情報保持させるため、attributesメソッドでデータ整形。

    session["devise.regist_data"][:user][:password] = params[:user][:password] 
    #前述で含まれなかった情報を代入。


    @destination = @user.build_destination 
    #build_destinationメソッドはhas_one :destinationのアソシエーションを設定すると使用可。関連づけのあるnewメソッドのようなもの。
    render :new_destination #登録2ページ目に遷移
  end

  
  
  def create_destination
    @user = User.new(session["devise.regist_data"]["user"])
    #session["devise.regist_data”]の中の["user”]というハッシュの情報を@userに代入している。

    @destination = Destination.new(destination_params)
    unless @destination.valid?
      flash.now[:alert] = @destination.errors.full_messages
      render :new_destination and return
    end
    @user.build_destination(@destination.attributes) #送られてきたparamsをbuild_ship_addressを用いて@userに代入
    @user.save
    session["devise.regist_data"]["user"].clear #sessionを明示的に削除 セキュリティ上必要
    sign_in(:user, @user) #登録後ログイン状態になるようにしている
    redirect_to root_path
    flash[:notice] = "新規会員登録が完了しました"
  end

  
  protected

  def birth_date_join(date)
    require "date"
    # date = params[:user][:birth_date]
    Date.new date["birth_date(1i)"].to_i,date["birth_date(2i)"].to_i,date["birth_date(3i)"].to_i
  end
   
  def destination_params
    params.require(:destination).permit(:destination_family_name, :destination_first_name, :destination_family_name_kana,:destination_first_name_kana, :post_code, :pref_id, :city, :house_number,:building_name,:phone_number)
  end
  # def new
  #   @user = User.new
  #   @user.build_destination
  # end

  # def create
  #   @user = User.new(user_params)
  #   @user.save
  #   # redirect_to root_path(@user)
  # end
  
  # private

  # def user_params
  #   params.require(:user).permit(:nickmame,profile_attributes:[],destination_attributes:[],:pref_id).merge(user_id: current_user.id)
  # end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  #   user = User.new(configure_sign_up_params)
  #   user.save
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:family_name,:first_name,:family_name_kana,:first_name_kana,:birth_date,destination_attributes:[:id, :destination_family_name,:destination_first_name,:destination_family_name_kana,:destination_first_name_kana,:post_code,:pref,:city,:house_number,:building_name,:phone_number]])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'payjp'
  before_action :authenticate_user!
  before_action :set_credit, only: [:buy,:confirm]
  before_action :set_item, only: [:buy,:confirm]
  


  def show
    @parents = Category.where(ancestry: nil) 
    @items = Item.where(seller_id: params[:id]).includes(:images).order('created_at DESC')
    @credit_information = Credit.where(user_id: current_user.id)
    @user = User.find(params[:id])
  end

  def edit

  end

  def confirm
    @image = @item.images.first
    @credit = @set_credit.first
    @destination = Destination.find(current_user.id)
    if @credit.blank?
      redirect_to controller: "credits", action: "new"
      flash[:alert] = 'クレジットカードを登録してください'
    else
    
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(@credit.customer_id)
      @default_card_information = customer.cards.retrieve(@credit.card_id)
    end
  end

  def buy
    @credit = @set_credit.first
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
    Payjp::Charge.create(
    amount: @item.price,
    customer: @credit.customer_id,
    currency: 'jpy',
  )
  redirect_to action: 'done_buy', id: @item
  end

  def done_buy
    @buy_item = Item.find(params[:id])
    if @buy_item.update(buyer_id: current_user.id)
    redirect_to root_path
    flash[:alert] = '購入が完了しました' 
    else
    redirect_to confirm_user_path
    flash[:alert] = '購入に失敗しました'
    end
  end

  private

  def set_credit
    @set_credit = Credit.where(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_items-for_user_main_screen.html.haml
.Pictures-list
  - if @items.present?
    - @items.each do |item|
      .Pictures-list__items
        - if item.buyer.present?
          .Pictures-list__items__status
            .Pictures-list__items__status__inner
              Sold
        = link_to item_path(item.id), class:".Pictures-list__items__link" do
          %figure.Pictures-list__items__link__picture
            = image_tag item.images.first.url.url
          .Pictures-list__items__link__texts
            %h3.pict-name
              = item.name
            .pict-detail
              %ul
                %li 
                  = "#{item.price}円"
                %li
                  = icon('fa', 'star likeIcon')
              %p (税込)

app/views/users/_user_main_screen.html.haml
= render 'layouts/header'

.Main-screen
  .Main-screen__profile
    .Main-screen__profile__icon
      = icon('far', 'user-circle')
      .Main-screen__profile__icon__user-name
        = link_to "#", class:"User-nickname" do
          = @user.nickname
  .Main-screen__contents 
    .Main-screen__contents__media
      = link_to "https://www.facebook.com/", class: "Facebook-btn" do
        = icon('fab', 'facebook-square')
      = link_to "https://twitter.com/", class: "Twitter-btn" do
        = icon('fab', 'twitter')
      = link_to "https://www.instagram.com/", class: "Line-btn" do
        = icon('fab', 'line')
    .Main-screen__contents__details
      - if current_user.id == @user.id
        .Main-screen__contents__details__credit
          .Main-screen__contents__details__credit--registration
            - if @credit_information.present?
              = link_to 'クレジットカード情報削除', delete_credits_path, class: "card-delete"
              = icon('fas', 'arrow-right')
            - else
              = link_to 'クレジットカード情報登録', new_credit_path, class: "card-regis", "data-turbolinks": false
              = icon('fas', 'arrow-right')
          .Main-screen__contents__details__account
            .Main-screen__contents__details__account--logout
              = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout-btn"
              = icon('fas', 'arrow-right')
    .Main-screen__contents__items-box
      .Main-screen__contents__items-box__head
        この出品者の商品
      .Main-screen__contents__items-box__goods
        = render 'items-for_user_main_screen'
      
= render 'layouts/exhibition'

= render 'layouts/aside'

= render 'layouts/footer'

app/views/users/confirm.html.haml
.Around
  .Around__logo
    = image_tag 'logo/logo.png', class: "image_tag1", alt: 'トップのロゴ'
  .Around__contents
    .Around__contents__string
      購入内容の確認
    .Around__contents__goods
      .Around__contents__goods__image
        = image_tag @image.url.url, size: '70x70', alt: '商品の仮写真'
      .Around__contents__goods__item-name
        = @item.name
        .Around__contents__goods__item-name__details
          %span.details-string 送料込み(税込)
          %span.details-price 
            = "#{@item.price}円"
    .Around__contents__price
      .Around__contents__price__string
        支払い金額
        .Around__contents__price__string--point
          =icon('fas', 'square')
          %span.point-string-left ポイント
          %span.point-string-right 所持ポイント：P0
      .Around__contents__price--amount
        = "#{@item.price}円"
    .Around__contents__method-payment
      .Around__contents__method-payment--string
        支払い方法
      .Around__contents__method-payment--add
        .card-group
          .card-group__title
            %label クレジットカード
            %br
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            = form_tag(delete_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
        -# =icon('far', 'plus-square')
        -# 登録してください
    .Around__contents__delivery-address
      .Around__contents__delivery-address--string
        配送先
      .Around__contents__delivery-address--add
        = "〒#{@destination.post_code}"
        %br
        = @destination.pref.name
        = @destination.city
        = @destination.house_number
        = @destination.building_name
        %br
        = @destination.destination_family_name 
        = @destination.destination_first_name  
        -# =icon('far', 'plus-square')
        -# 登録してください
    .Around__contents__buy-botton
      -# = form_with model: @item do |form|
      -# = form_with model: [:admin, @user], local: true do |f| 
      = form_tag(action: :buy, method: :post, id: @item.id, user_id: current_user.id) do
        %button.buy-btn 購入する
        
  .Around__footer-logo
    = image_tag 'logo/logo-white.png', size: '140x70', class: "image_tag2", alt: 'フッターのロゴ'

app/views/users/done_buy.html.haml
購入が完了しました
%p
  = link_to root_path do
    トップページへ

app/views/users/index.html.haml
.wrapper
  = render 'layouts/notifications'
  = render "user_main_screen"

app/views/users/show.html.haml
.wrapper
  = render 'layouts/notifications'
  = render "user_main_screen"