config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get  'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end
  root 'items#index'
 
  resources :items do
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :credits,only:[:index,:new,:show,:edit,:update]do
    collection do
      #payjpでトークン化を行う
      post 'pay', to: 'credits#pay'
      #カード削除
      post 'delete', to: 'credits#delete'
      #カード情報入力
      post 'show', to: 'credits#show'
    end
  end
    
  resources :users do
    collection do
      post 'buy',to: 'users#buy'
      get  'done_buy',to: 'users#done_buy'
    end
    member do
      get 'confirm'
    end
  end
  resources :brands
  resources :comments
  resources :destinations
  resources :categories, only: [:index, :show]
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user

  validates :customer_id,:card_id,presence: true
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  require "payjp"

  def new
    credit = Credit.where(user_id: current_user.id)
    redirect_to action: "show" if credit.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @credit = Credit.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit.save
        redirect_to user_path(current_user.id)
        flash[:notice] = 'クレジットカードの登録が完了しました'
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    credit = Credit.where(user_id: current_user.id).first
    if credit.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(credit.customer_id)
      customer.delete
      credit.delete
      redirect_to user_path(current_user.id)
      flash[:alert] = 'クレジットカードの情報を削除しました'
    end
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    credit = Credit.where(user_id: current_user.id).first
    if credit.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(credit.customer_id)
      @default_card_information = customer.cards.retrieve(credit.card_id)
    end
  end

  def edit
    credit = Credit.where(user_id: current_user.id).first
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(credit.customer_id)
      @default_card_information = customer.cards.retrieve(credit.card_id)
  
  end


  def update
    @credit = Credit.where(user_id: current_user.id)
    if Credit.update(params[:id])
      redirect_to user_path
      flash[:notice]= 'クレジットカード情報を登録しました'
    else
      render :edit
    end
  end



end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/edit.html.haml
.form-wapper
  = render 'layouts/notifications'
  = form_tag(pay_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
    .signup-content_text
      .form-group.form-group_text
        %label.form-group_label カード番号
        %span.essential 必須
      = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      .form-group.form-group_text.card_label
        %label.form-group_label 有効期限
        %span.essential 必須
    .form-group
      .form-flex#form-flex
        .birth-group
          %select#exp_month{name: "exp_month", type: "text", class: "select-default"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %i.fa.fa-chevron-down
        %span.birth-group__month 月
    .birth-group
      %select#exp_year{name: "exp_year", type: "text", class: "select-default2"}
        %option{value: ""} --
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
        %option{value: "2030"}30
      %i.fa.fa-chevron-down.down
    %span.birth-group__year 年
    .form-group.form-group_text.card_code
      %label.form-group_label セキュリティコード
      %span.essential3 必須
    = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
    #card_token
    .form-group
    = submit_tag "登録する", id: "token_submit"
    

.card-group
  .card-group__title
    %label クレジットカード一覧
    %br
    = "**** **** **** " + @default_card_information.last4
    %br
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year
    = form_tag(delete_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %input{ type: "hidden", name: "card_id", value: "" }
      %button.btn_delate  削除する

app/views/credits/new.html.haml
.Credit-background
  .Credit-header
    = link_to root_path, class: "HeaderInner__icon" do
      = image_tag 'logo/logo.png', size:'200x50', alt: 'ロゴです'
  .Credit-contents
    .Credit-contents__integer
      支払い方法
    .Credit-contents__input
      .form-wapper
        = render 'layouts/notifications'
        = form_tag(pay_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
          .signup-content_text
            .form-group.form-group_text
              %label.form-group_label カード番号
              %span.essential 必須
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            .form-group.form-group_text.card_label
              %label.form-group_label 有効期限
              %span.essential 必須
          .form-group
            .birth-group
              .birth-group__month
                %select#exp_month{name: "exp_month", type: "text", class: "select-default"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %span.birth-group__month-string 月
              .birth-group__year
                %select#exp_year{name: "exp_year", type: "text", class: "select-default2"}
                  %option{value: ""} --
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                  %option{value: "2030"}30
                %span.birth-group__year-string 年
          .form-group.form-group_text.card_code
            %label.form-group_label セキュリティコード
            %span.essential 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          #card_token
          .form-group
          = submit_tag "登録する", id: "token_submit", class: "registration-btn"

app/views/credits/show.html.haml
.Credit-background
  .Credit-header
    = link_to root_path, class: "HeaderInner__icon" do
      = image_tag 'logo/logo.png', size:'200x50', alt: 'ロゴです'
  .card-group
    .card-group__title
      クレジットカード一覧
    .card-group__contents
      %br
      = "**** **** **** " + @default_card_information.last4
      %br
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      = "有効期限" + exp_month + " / " + exp_year
      = form_tag(delete_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button.btn_delate  削除する