config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get  'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end
  root 'items#index'
 
  resources :items do
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :credits,only:[:index,:new,:show,:edit,:update]do
    collection do
      #payjpでトークン化を行う
      post 'pay', to: 'credits#pay'
      #カード削除
      post 'delete', to: 'credits#delete'
      #カード情報入力
      post 'show', to: 'credits#show'
    end
  end
    
  resources :users do
    collection do
      post 'buy',to: 'users#buy'
      get  'done_buy',to: 'users#done_buy'
    end
    member do
      get 'confirm'
    end
  end
  resources :brands
  resources :comments
  resources :destinations
  resources :categories, only: [:index, :show]
end

app/models/item.rb
class Item < ApplicationRecord
  # has_many :comments, dependent: -destroy-belongs_to :user
  has_many :comments, dependent: :destroy
  belongs_to :user,optional: true
  belongs_to :category
  has_many :favorites
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_one :evaluation
  belongs_to :seller, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :pref
  validates :name, :introduction, :price, :condition, :preparation_day, :pref, :postage_burden, presence:{ message: "を入力してください"}
  validates :images, presence: { message: "を入力してください"}
  validates :price, :numericality => { greater_than: 300, less_than: 9999999 } 


  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :confirm]
  before_action :move_to_index, except: [:index, :show]

  def index
    @items = Item.includes(:images).order('created_at DESC').limit(5)
    @parents = Category.where(ancestry: nil)    
  end
  
  def new
    @item = Item.new
    @item.images.build

    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent_array = Category.where(ancestry: nil)


  end

    # 以下全て、formatはjsonのみ
    # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

    # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def create

    @item = Item.create!(item_params)
    if @item.save
      redirect_to root_path
    else
      unless @item.images.present?
        @item.images.new
        render 'new'
      else
        render 'new'
      end
    end
  end
  

  def show
    @item = Item.includes(:images).order('created_at DESC').find(params[:id])
    @parents = Category.where(ancestry: nil)
  end



  def destroy
    item = Item.find(params[:id])
    if item.seller_id == current_user.id && item.destroy
      redirect_to user_path(current_user.id)
    end
  end

  def edit


  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :brand, :condition, :pref_id, :preparation_day, :category_id, :postage_burden, images_attributes: [:url, :_destroy, :id]).merge(seller_id: current_user.id)
  end
  
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_credits.html.haml
.top-bar
  
.second-bar
  .second-bar__one
    .second-bar__one__number
      .second-bar__one__number__text-required
        .second-bar__one__number__text-required__text
        .second-bar__one__number__text-required__required
      .second-bar__one__number__number-room
        .second-bar__one__number__number-room__text
    .second-bar__one__icon
      .second-bar__one__icon__one
      .second-bar__one__icon__two
      .second-bar__one__icon__three
  .second-bar__two
    .second-bar__two__text-required
      .second-bar__two__text-required__text
      .second-bar__two__text-required__required
    .second-bar__two__month-yaer
      .second-bar__two__month-yaer__month
      .second-bar__two__month-yaer____text
      .second-bar__two__month-yaer__yaer
      .second-bar__two__month-yaer__text
  .second-bar__three
    .second-bar__three__text-required
      .second-bar__three__text-required__text
      .second-bar__three__text-required__required
    .second-bar__three__security
      .second-bar__three__security__text
  .second-bar__register
    .second-bar__register__text

app/views/items/_pickup-category.html.haml
%section.pickup-menu
  %h2.pickup-menu__title ピックアップカテゴリー
  .pickup-menu__info
    .list-title
      = link_to "#", class:"list-title__link" do
        %h3.list-title__link__name 新規投稿商品
    .post-list
      - @items.each do |item|
        .post-list__items
          - if item.buyer.present?
            .post-list__items__status
              .post-list__items__status__inner
                Sold
          = link_to item_path(item.id), class:"post-list__items__link" do
            %figure.post-list__items__link__picture
              = image_tag item.images.first.url.url
            .post-list__items__link__texts
              %h3.pict-name
                = item.name
              .pict-detail
                %ul
                  %li 
                    = "#{item.price}円"
                  %li
                    = icon('fa', 'star likeIcon')
                    0
                %p (税込)

app/views/items/edit.html.haml
.new
  .title 
    = link_to root_path do
      = image_tag 'logo/logo.png',size:'150x40',alt: 'ロゴです'
  = form_with model: @item, class: "new-inputs" do |f|
    .new-inputs__images
      %label 出品画像
      %span.required 必須 
      %p 最大10枚までアップロードできます。   
      #image-box
        #previews
          - if @item.persisted?
            - @item.images.each_with_index do |image, i|
              = image_tag image.url.url, data: { index: i }, width: "130", height: '70',required: "true"
        = f.fields_for :images do |image|
          .js-file_group{"data-index" => "#{image.index}"}
            = image.file_field :url, class: 'js-file'
            %br/
            %span.js-remove 削除
          - if @item.persisted?
            = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
        - if @item.persisted?
          .js-file_group{"data-index" => "#{@item.images.count}"}
            = file_field_tag :url, name: "item[images_attributes][#{@item.images.count}][url]", class: 'js-file'
            %span.js-remove 削除


      .upload_image
    .new-inputs__name
      %label 商品名
      %span.required 必須 
      .input-form
        = f.text_field :name, placeholder:  "40文字まで",class:  "smallform",autocomplete:"off",required: "true"
      .instruction 入力してください  
    .new-inputs__introduction
      %label 商品の説明
      %span.required 必須 
      .input-form
        = f.text_area :introduction, placeholder:  "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）",class:  "bicform",autocomplete:"off",rows:"7",required: "true"
    .new-inputs__details
      %p 商品の詳細
      .exhibitionPage__main__contents__detail__category
        .exhibitionPage__main__contents__detail__category__title
        %label カテゴリー
        %span.required 必須 
        .exhibitionPage__main__contents__detail__category__choose
          = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name,  { include_blank: "---", selected:'---'}, {id: 'parent_category',required: "true"}
        .instruction ここを選択し直してください  
      %label ブランド
      %span.any 任意
      = f.text_field :brand, placeholder:  "例：シャネル",class:  "smallform",autocomplete:"off"
      %label 状態
      %span.required 必須 
      .select
        = f.select :condition, [["新品、未使用", "新品、未使用"],["未使用に近い", "未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], { include_blank: '選択してください'}, { class: 'form-control' , required: true }
      .instruction 選択してください  
    .new-inputs__delivery
      %p 配送について 
      %label 状態
      %span.required 必須 
      .select
        = f.select :postage_burden, [["送料込み(出品者負担)", "送料込み(出品者負担)"],["着払い(購入者負担)", "着払い(購入者負担)"]], { include_blank: '選択してください'}, { class: 'form-control' , required: true }
      .instruction 選択してください  
      %label 発送元地域
      %span.required 必須 
      .select
        = f.collection_select(:pref_id, Pref.all, :id, :name, {include_blank: "---"}, {class: "select", required: true } ) 

      .instruction 選択してください  
      %label 発送までの日数
      %span.required 必須 
      .select
        = f.select :preparation_day, [["1~2日で発送", "1~2日で発送"],["2~3日で発送", "2~3日で発送"],["4~7日で発送", "4~7日で発送"]], { include_blank: '選択してください'}, { class: 'form-control' , required: true }
      .instruction 選択してください
    .new-inputs__price
      %p 価格（¥300〜9,999,999）
      %label 販売価格
      %span.required 必須
      %span.yen ¥
      = f.text_field :price, placeholder:  "0",class:  "smallform",autocomplete:"off",required: "true"
      .instruction 300以上9999999以下で入力してください
    .new-inputs__btns
      .btn-exhibtion
        = f.submit "出品する", {class:"btn-exhibtion", tabindex:"0"}
      .btn-top
        = link_to root_path do 
          もどる
    .new-inputs__warning
      %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
= render 'layouts/footer'

app/views/items/index.html.haml
= render 'layouts/notifications'
= render 'layouts/header'
.main
  %section.description
    .description__info
      %h2.description__info__title
        人生を変えるフリマアプリ
      %p.description__info__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .description__info__btns
        = link_to "#", class:"app-store" do
          = image_tag 'icon/AppStore.png', size:'180x54'
        = link_to "#", class:"google-play" do
          = image_tag 'icon/GooglePlay.png', size:'200x82'
  %section.reason-area
    %h2.reason-area__title
      FURIMAが選ばれる3つの理由
    %ul.point-list
      %li.point-list__box
        .point-list__box__picture
          %span.nunber 1
          = image_tag 'pict/pict-reason-01.jpg'
        %h3.point-list__box__subtitle
          %span 3分
          ですぐに出品
        %p.point-list__box__text
          スマホで入力するだけで簡単に出品できる
      %li.point-list__box
        .point-list__box__picture
          %span.nunber 2
          = image_tag 'pict/pict-reason-02.jpg'
        %h3.point-list__box__subtitle
          %span シンプル
          で使いやすい
        %p.point-list__box__text
          めんとくさい入力は必要なく、検索も購入もスムーズ！
      %li.point-list__box
        .point-list__box__picture
          %span.nunber 3
          = image_tag 'pict/pict-reason-03.jpg'
        %h3.point-list__box__subtitle
          手数料
          %span 業界最安値
        %p.point-list__box__text
          最大3%でお得に出品&購入！
  %section.popularity
    .popularity__info
      %h2.popularity__info__title 会員数日本一位
      %p.popularity__info__text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        欲しかったあの商品に出会えるかもしれません。
      .popularity__info__btns
        = link_to "#", class:"app-store" do
          = image_tag 'icon/AppStore.png', size:'180x54'
        = link_to "#", class:"google-play" do
          = image_tag 'icon/GooglePlay.png', size:'200x82'
  %section.charactrristic
    %h2.charactrristic__title FURIMAの特徴
    .charactrristic__info
      %section.feature
        %figure.feature__image
          = image_tag 'icon/icon-01.png'
        %h3.feature__subtitle
          簡単に売り買いできる
        %p.feature__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.feature
        %figure.feature__image
          = image_tag 'icon/icon-03.png'
        %h3.feature__subtitle
          売上金は即日振込みに対応
        %p.feature__text
          午前9時までに振り込みを依頼いただければ、翌日に指定の口座に入金いたします！
      %section.feature
        %figure.feature__image
          = image_tag 'icon/icon-04.png'
        %h3.feature__subtitle
          様々な支払いに対応
        %p.feature__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  = render 'pickup-category'
= render 'layouts/aside'
= render 'layouts/footer'
= render 'layouts/exhibition'

app/views/items/new.html.haml
.new
  .title 
    = link_to root_path do
      = image_tag 'logo/logo.png',size:'150x40',alt: 'ロゴです'
  = form_with model: @item, class: "new-inputs" do |f|
    .new-inputs__images
      %label 出品画像
      %span.required 必須 
      %p 最大10枚までアップロードできます。   
      #image-box
        = f.fields_for :images do |image|
          .js-file_group{"data-index" => "#{image.index}"}
            = image.file_field :url, class: 'js-file',required: "true"
            %br/
            %span.js-remove 削除
      .upload_image
    .new-inputs__name
      %label 商品名
      %span.required 必須 
      .input-form
        = f.text_field :name, placeholder:  "40文字まで",class:  "smallform",autocomplete:"off",required: "true"
      .instruction 入力してください  
    .new-inputs__introduction
      %label 商品の説明
      %span.required 必須 
      .input-form
        = f.text_area :introduction, placeholder:  "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）",class:  "bicform",autocomplete:"off",rows:"7",required: "true"
    .new-inputs__details
      %p 商品の詳細
      .exhibitionPage__main__contents__detail__category
        .exhibitionPage__main__contents__detail__category__title
        %label カテゴリー
        %span.required 必須 
        .exhibitionPage__main__contents__detail__category__choose
          = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category',required: "true"}
        .instruction 選択してください  
      %label ブランド
      %span.any 任意
      = f.text_field :brand, placeholder:  "例：シャネル",class:  "smallform",autocomplete:"off"
      %label 状態
      %span.required 必須 
      .select
        -# = f.select :condition, [["選択してください。", nil],["新品、未使用", "新品、未使用"],["未使用に近い", "未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]]
        = f.select :condition, [["新品、未使用", "新品、未使用"],["未使用に近い", "未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], { include_blank: '選択してください'}, { class: 'form-control' , required: true }

      .instruction 選択してください  
    .new-inputs__delivery
       
      %label 配送について 
      %span.required 必須 
      .select
        = f.select :postage_burden, [["送料込み(出品者負担)", "送料込み(出品者負担)"],["着払い(購入者負担)", "着払い(購入者負担)"]], { include_blank: '選択してください'}, { class: 'form-control' , required: true }
      .instruction 選択してください  
      %label 発送元地域
      %span.required 必須 
      .select
        = f.collection_select(:pref_id, Pref.all, :id, :name, {include_blank: "---"}, {class: "select", required: true } ) 

      .instruction 選択してください  
      %label 発送までの日数
      %span.required 必須 
      .select
        = f.select :preparation_day, [["1~2日で発送", "1~2日で発送"],["2~3日で発送", "2~3日で発送"],["4~7日で発送", "4~7日で発送"]], { include_blank: '選択してください'}, { class: 'form-control' , required: true }
      .instruction 選択してください
    .new-inputs__price
      %p 価格（¥300〜9,999,999）
      %label 販売価格
      %span.required 必須
      %span.yen ¥
      = f.text_field :price, placeholder:  "0",class:  "smallform",autocomplete:"off",required: "true"
      .instruction 300以上9999999以下で入力してください
    .new-inputs__btns
      .btn-exhibtion
        = f.submit "出品する", {class:"btn-exhibtion", tabindex:"0"}
      .btn-top
        = link_to root_path do 
          もどる
    .new-inputs__warning
      %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
= render 'layouts/footer'

app/views/items/show.html.haml
= render 'layouts/header'
.Main
  .main-show-view
    .main-show-view__item-name
      .main-show-view__item-name__name-zoon
        = @item.name
    .main-show-view__image-information
      .main-show-view__image-information__image
        - if @item.buyer.present?
          .Status
            .Status__inner
              Sold
        = image_tag @item.images.first.url.url
        %ul
          %li
            - @item.images.each do |i|
              = image_tag i.url.url, size: '80x80'
      .main-show-view__image-information__information
        %table{border: "1"}
          %tbody
            %tr
              %th 出品者
              %td
                = link_to user_path(@item.seller.id) , class: "Exhibitor-category" do
                  = @item.seller.nickname
            %tr
              %th カテゴリー
              %td
                = link_to category_path(@item.category.parent.parent.id), class: "Exhibitor-category" do
                  = @item.category.parent.parent.name
                  %br
                = link_to category_path(@item.category.parent.id), class: "Exhibitor-category" do
                  = @item.category.parent.name
                  %br
                = link_to category_path(@item.category.id), class: "Exhibitor-category" do
                  = @item.category.name
            %tr
              %th ブランド
              %td 
                = @item.brand
            %tr
              %th 商品の状態
              %td 
                = @item.condition
            %tr
              %th 配送料の負担
              %td 
                = @item.postage_burden
            %tr
              %th 配送日元地域
              %td 
                = @item.pref.name
            %tr
              %th 配送日の目安
              %td 
                = @item.preparation_day
    .main-show-view__comment-exc
      .main-show-view__comment-exc__price-tax
        .main-show-view__comment-exc__price-tax__price
          = "#{@item.price}円"
        .main-show-view__comment-exc__price-tax__tax
          (税込) 送料込み
      .main-show-view__comment-exc__comment
        = safe_join @item.introduction.split("\n"),tag(:br)

  - if @item.buyer.present?
    .Soldout
      売り切れました
  - else
    - if user_signed_in? 
      - if current_user.id == @item.seller_id
        .Change
          .Change__button
            = link_to edit_item_path, class: "edit-btn" do
              .edit-btn__text
                商品の編集
            = link_to item_path(params[:id]), method: :delete, class: 'destroy-btn', data: {confirm: "削除しますか？"} do
              .destroy-btn__text
                この商品を削除する
      - else 
        .Buy
          = link_to  confirm_user_path(@item.id), class:"Buy-btn","data-turbolinks": false do
            .Buy-btn__text
              購入画面に進む
    - else
      .Login
        .Login__sign
          = link_to new_user_registration_path, class:"Sign-up-btn" do
            .Sign-up-btn__text
              新規会員登録をして購入画面に進む
          = link_to  new_user_session_path, class:"Sign-in-btn" do
            .Sign-in-btn__text
              ログインをして購入画面に進む
= render 'layouts/aside'
= render 'layouts/footer'