config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get  'destinations', to: 'users/registrations#new_destination'
    post 'destinations', to: 'users/registrations#create_destination'
  end
  root 'items#index'
 
  resources :items do
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :credits,only:[:index,:new,:show,:edit,:update]do
    collection do
      #payjpでトークン化を行う
      post 'pay', to: 'credits#pay'
      #カード削除
      post 'delete', to: 'credits#delete'
      #カード情報入力
      post 'show', to: 'credits#show'
    end
  end
    
  resources :users do
    collection do
      post 'buy',to: 'users#buy'
      get  'done_buy',to: 'users#done_buy'
    end
    member do
      get 'confirm'
    end
  end
  resources :brands
  resources :comments
  resources :destinations
  resources :categories, only: [:index, :show]
end

app/views/layouts/_aside.html.haml
//ここからアサイド

%aside.AppBanner
  .ABInner
    %h2.ABInner__Title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.ABInner__Text
      今すぐ無料ダウンロード！
    .ABInner__Icon
      = link_to "https://www.apple.com/jp/ios/app-store/",class:'ABInner__Icon--aBtn' do
        = image_tag 'icon/AppStore.png',size: '180x54', alt: 'AppStoreのアイコン'
      = link_to "https://play.google.com/store?hl=ja",class:'ABInner__Icon--gBtn' do
        = image_tag 'icon/GooglePlay.png',size: '200x82', alt: 'GooglePlayのアイコン'

app/views/layouts/_exhibition.html.haml
= link_to new_item_path do
  .exhibition-button
    .exhibition-button__text
      出品する
    .exhibition-button__icon
      = image_tag 'icon/icon_camera.png',size: '54x54',alt: 'ロゴです'

app/views/layouts/_footer.html.haml
//ここからフッター

%footer.CommonFooter
  %ul.CommonFooter__Contents
    %li.CommonFooter__Content
      %h2.CommonFooter__ContentHead
        FURIMAについて
      %ul.CommonFooter__Lists
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            会社概要(運営会社)
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            プライバシーポリシー
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            FURIMA利用規約
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            ポイントに関する特約
    %li.CommonFooter__Content
      %h2.CommonFooter__ContentHead
        FURIMAを見る
      %ul.CommonFooter__Lists
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            カテゴリー一覧
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            ブランド一覧
    %li.CommonFooter__Content
      %h2.CommonFooter__ContentHead
        ヘルプ & ガイド
      %ul.CommonFooter__Lists
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            FURIMAガイド
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            FURIMAロゴ利用ガイドライン
        %li.CommonFooter__List
          = link_to "#" , class:"CommonFooter__list" do
            お知らせ
  .CommonFooter__Logo
    = link_to "#", class: "CommonFooter__logo" do
      = image_tag 'logo/logo-white.png',size: '160x46',alt: 'ロゴです'
    %p.CommonFooter__Copyright
      © FURIMA

app/views/layouts/_header.html.haml
%header.CommonHeader
  .HeaderInner
    .HeaderInner__Main
      %h1.HeaderInner__Icon
        = link_to root_path,class: "HeaderInner__icon" do
          = image_tag 'logo/logo.png',size:'150x40',alt: 'ロゴです'
      .HeaderInner__SearchBox
        = form_with url: '#',class: 'HeaderInner__TextBox' ,local: true do |f|
          .HeaderInner__Input
            = f.text_field :keyword, placeholder: 'キーワードから探す',class: 'HeaderInner__TextField' 
            %button{type: "submit", class:'HeaderInner__Btn'}
              = image_tag 'icon/icon-search 1.png',size: '20x20', alt: '虫眼鏡の写真', class: 'HeaderInner__Submit'
                  
    .HeaderInner__Nav
      %ul.HeaderInner__Left
        %li.HeaderInner__List
          = link_to "#" ,class:'HeaderInner__Default' do
            カテゴリーから探す    
          %ul.HeaderInner__parents
            - @parents.each do |parent|
              %li.HeaderInner__parent{value: parent.id}
                = link_to category_path(parent.id) ,class:"HeaderInner__Left--first" do
                  .HeaderInner__parent--name
                    = parent.name   
                  %ul.HeaderInner__children
                    - parent.children.each do |child|
                      %li.HeaderInner__child{value: child.id}
                        = link_to category_path(child.id) ,class:"HeaderInner__Left--first" do
                          .HeaderInner__children--name
                            = child.name   
                        %ul.HeaderInner__grandchildren
                          - child.children.each do |grandchild|
                      
                            %li.HeaderInner__grandchild{value: grandchild.id}
                              = link_to category_path(grandchild.id) ,class:"HeaderInner__Left--first" do
                                .HeaderInner__grandchildren--name
                                  = grandchild.name  
        %li.HeaderInner__List--Brand
          = link_to "#",class:"HeaderInner__Left--second" do
            ブランド
      %ul.HeaderInner__Right
        - if user_signed_in?
          %li.HeaderInner__RightList
            = link_to   destroy_user_session_path,class:"HeaderInner__Right--first", method: :delete do
              ログアウト
            %li.HeaderInner__List--Right
              = link_to   user_path(current_user.id),class:"HeaderInner__Right--second" do
                .HeaderInner__List--icon
                  = image_tag "icon/member_photo_noimage_thumb.png",size:'30x30'
                .HeaderInner__List--Mypage
                  = current_user.nickname + 'のマイページ'
        - else
          %li.HeaderInner__RightList
            = link_to  new_user_session_path , class:"HeaderInner__Right--first" do
              ログイン
            %li.HeaderInner__List--New
              = link_to new_user_registration_path, class:"HeaderInner__List--new" do
                新規会員登録
      

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FleamarketSample79h
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/layouts/header.html.haml
%header.CommonHeader
  .HeaderInner
    .HeaderInner__Main
      %h1.HeaderInner__Icon
        = link_to "#",class: "HeaderInner__icon" do
          = image_tag 'logo/logo.png',size:'150x40',alt: 'ロゴです'
      .HeaderInner__SearchBox
        = form_with url: '#',class: 'HeaderInner__TextBox' ,local: true do |f|
          .HeaderInner__Input
            = f.text_field :keyword, placeholder: 'キーワードから探す',class: '.HeaderInner__TextField ' 
            %button{type: "submit", class:'HeaderInner__Btn'}
              = image_tag 'icon/icon-search 1.png',size: '20x20', alt: '虫眼鏡の写真', class: 'HeaderInner__Submit'
                  
    .HeaderInner__Nav
      %ul.HeaderInner__Left
        %li.HeaderInner__List
          カテゴリー
        %li.HeaderInner__List
          ブランド
      %ul.HeaderInner__Right
        %li.HeaderInner__List
          ログイン
        %li.HeaderInner__List
          新規会員登録